version: '3.8'

services:
  app:
    image: peepeds/url-shortener:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/url-shortener-db
      - BASE_URL=http://localhost:3000/
    depends_on:
      - mongo
    networks:
      - url-shortener-network
  
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/db/data
    networks:
      - url-shortener-network
  
volumes:
  mongo-data:
    driver: local

networks:
  url-shortener-network:
    driver: bridge
  